**Import TensorFlow**

Let's get started,first step is importing the tensorflow module.As of TensorFlow 2, eager execution is turned on by default. This enables a more interactive frontend to TensorFlow, the details of which we will discuss much later


In [0]:
import tensorflow as tf

**Version Check**

In [2]:
#rc- Release Candidate

print(tf.__version__)

2.2.0


**Tensors in 2.0**

A Tensor is a multi-dimensional array. Similar to NumPy ndarray objects, tf.Tensor objects have a data type and a shape. Additionally, tf.Tensors can reside in accelerator memory (like a GPU). TensorFlow offers a rich library of operations (tf.add, tf.matmul, tf.linalg.inv etc.) that consume and produce tf.Tensors. These operations automatically convert native Python types, for example:

1.  Printing Hello Wrold
2.  Printing two numbers
3.  Vector Sum
4.  Sum of squares
5.  Computing the sum of elements across dimensions of a tensor.
6.  Seprate Sum
7.  Operator overloading is also supported
8.  Matrix Multiplication
9.  Shape of matrix
10. Checking datatype of matrix







In [3]:
# Hello Wrold 
msg = tf.constant('TensorFlow 2.0 Hello World')
tf.print(msg)

TensorFlow 2.0 Hello World


In [4]:
#Adding wo numbers
print(tf.add(1, 2))

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
#Vector Sum
print(tf.add([1.0, 2.0], [3, 4]))

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [6]:
#Sum of squares
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [7]:
#Computing the sum of elements across dimensions of a tensor.
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(6, shape=(), dtype=int32)


In [8]:
#Seprate Sum
a = tf.constant([1, 2])
b = tf.constant([3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor([-2 -2], shape=(2,), dtype=int32)
tf.Tensor([3 8], shape=(2,), dtype=int32)
tf.Tensor([0.33333333 0.5       ], shape=(2,), dtype=float64)


In [9]:
# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [10]:
#Matrix Multiplication
x = tf.matmul([[1]], [[2, 3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [11]:
#Shape of matrix
print(x.shape)

(1, 2)


In [12]:
#Checking datatype of matrix
print(x.dtype)

<dtype: 'int32'>



The most obvious differences between NumPy arrays and tf.Tensors are:

1. Tensors can be backed by accelerator memory (like GPU, TPU).
2. Tensors are immutable.